### ISSUE TITLE
已经安装完依赖和下载model了，为啥启动会报错ModuleNotFoundError: No module named 'sentencepiece'

### ISSUE THREAD

**Issue by jiangsiYang** [KMnO4-zx/TinyAgent#1]
谢谢，错误如下
================ Loading model ================
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 719, in _load
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\kaka\.cache\huggingface\modules\transformers_modules\internlminternlm2-chat-20b\tokenization_internlm2_fast.py", line 35, in <module>
    from .tokenization_internlm2 import InternLM2Tokenizer
  File "C:\Users\kaka\.cache\huggingface\modules\transformers_modules\internlminternlm2-chat-20b\tokenization_internlm2.py", line 23, in <module>
    import sentencepiece as spm
ModuleNotFoundError: No module named 'sentencepiece'
python-BaseException

**Comment by KMnO4-zx** [comment]
那就"pip install sentencepiece"
